### ISSUE TITLE
Дебаг FSM

### ISSUE THREAD

**Issue by TonitaN** [Encapsulateed/tfl#2]
Тестировщик (мой TA) должен здесь предъявить ошибочные тесты на FSM, и помочь @Encapsulateed выявить структуры, в которых возникают ошибки.

**Comment by geogreck** [comment]
![image](https://github.com/Encapsulateed/tfl/assets/74151984/0e9327da-2480-4285-92d5-5a1a92c0b38b)

**Comment by TonitaN** [comment]
У вас какой-то альтернативный преобразователь FSM в изображение, я не понимаю, какой ДКА тут изображён, но если вашему напарнику всё понятно - то ок.

**Comment by geogreck** [comment]
> У вас какой-то альтернативный преобразователь FSM в изображение, я не понимаю, какой ДКА тут изображён, но если вашему напарнику всё понятно - то ок.

Преобразователь в язык DOT работает корректно, [вроде как](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0Arankdir%20%3D%20LR%0Adummy%20%5Bshape%3Dnone%2C%20label%3D%22%22%2C%20width%3D0%2C%20height%3D0%5D%0Aq0%20%5Blabel%20%3D%20%22q0%22%2C%20shape%20%3D%20circle%5D%0Aq1%20%5Blabel%20%3D%20%22q1%22%2C%20shape%20%3D%20circle%5D%0Aq2%20%5Blabel%20%3D%20%22q2%22%2C%20shape%20%3D%20doublecircle%5D%0Aq3%20%5Blabel%20%3D%20%22q3%22%2C%20shape%20%3D%20doublecircle%5D%0Aq4%20%5Blabel%20%3D%20%22q4%22%2C%20shape%20%3D%20doublecircle%5D%0Aq5%20%5Blabel%20%3D%20%22q5%22%2C%20shape%20%3D%20circle%5D%0Aq6%20%5Blabel%20%3D%20%22q6%22%2C%20shape%20%3D%20doublecircle%5D%0Adummy%20-%3E%20q0%0Aq0%20-%3E%20q1%20%5Blabel%20%3D%20b%5D%0Aq1%20-%3E%20q1%20%5Blabel%20%3D%20c%5D%0Aq1%20-%3E%20q2%20%5Blabel%20%3D%20a%5D%0Aq2%20-%3E%20q3%20%5Blabel%20%3D%20a%5D%0Aq3%20-%3E%20q4%20%5Blabel%20%3D%20a%5D%0Aq4%20-%3E%20q4%20%5Blabel%20%3D%20a%5D%0Aq0%20-%3E%20q5%20%5Blabel%20%3D%20c%5D%0Aq5%20-%3E%20q6%20%5Blabel%20%3D%20a%5D%0Aq0%20-%3E%20q5%20%5Blabel%20%3D%20a%5D%0A%7D)

**Comment by TonitaN** [comment]
Если выше - тоже его порождение, то кажется, мне пора спать.
P.S. - Вы же исправите лабу, правда?

**Comment by geogreck** [comment]
> Если выше - тоже его порождение, то кажется, мне пора спать. P.S. - Вы же исправите лабу, правда?

Порой лучший способ исправить ошибки, это начать всё сначала..

**Comment by TonitaN** [comment]
Ну мы ведь всё понимаем насчёт NP-полноты (с учётом ваших высоких знакомств, иначе и быть не может), ну пусть будет много вложенных циклов и всё медленно, но хоть на малых данных чтобы работало. Жду минимальный контрпример, ломающий лабу, в этой теме.

**Comment by Encapsulateed** [comment]
Здравствуйте и благодарим вас за обращение. Мы ценим Ваше доверие к нам. Хотим Вас уведомить, что наш технический отдел уже приступил к работе над адаптацией решения в соответствии с вашим запросом.

К сожалению, мы обнаружили, что разработчик не обладал достаточными знаниями о синтаксических деревьях, что привело к досадной ошибке. Однако мы уже приступили к ее устранению, и в ближайшие сроки все недочеты будут исправлены.

Благодарим вас за терпение и понимание.

С уважением ООО "Георгий и Алексей Солюшнс"

**Comment by TonitaN** [comment]
Звучит так, что придётся ждать ещё долго...

**Comment by geogreck** [comment]
@Encapsulateed просьба изучить поведение программы на следующих регулярных выраженииях
`c(((c*|(c(c)|(b)**(b)*#a*)(a)*)|b*)|(b)*)`
`(a|((a|b)|a#(a)b*|b*|(a)*))*|(a)*#((b)*)`
`(b)|(((b)|(a)|b#c|(b))|c)b*b*(a)*`

**Comment by TonitaN** [comment]
Не очень похоже на минимальные примеры. Есть гораздо проще.

**Comment by Encapsulateed** [comment]
> @Encapsulateed просьба изучить поведение программы на следующих регулярных выраженииях `c(((c*|(c(c)|(b)**(b)*#a*)(a)*)|b*)|(b)*)` `(a|((a|b)|a#(a)b*|b*|(a)*))*|(a)*#((b)*)` `(b)|(((b)|(a)|b#c|(b))|c)b*b*(a)*`

![graphviz (5)](https://github.com/Encapsulateed/tfl/assets/69109441/ec3b71a9-6b9e-4909-8e9a-bf7202cd82ea)
![graphviz (6)](https://github.com/Encapsulateed/tfl/assets/69109441/897aa734-4742-43b6-8afb-74b14adde676)
![graphviz (7)](https://github.com/Encapsulateed/tfl/assets/69109441/51fb6f6a-70c3-4aec-8d82-7771c5867cdd)

**Comment by Encapsulateed** [comment]
Уведомляем вас о внесении изменений в наименование нашей компании. С настоящего момента ООО "Георгий и Алексей Солюшнс" переименовано в ООО "Алексей Солюшнс" из-за внутренних проблем. 
Касательно технических сложностей с преобразованием Shuffle регулярного выражения в академическое, хотим сообщить, что проблема практически решена. Дополнительные подробности были отправлены на вашу электронную почту нашим техническим отделом.

**Comment by geogreck** [comment]
После их расставания я перестал верить в любовь

**Comment by TonitaN** [comment]
Завтра буду смотреть РК и эту лабу (с надеждой, что уже можно будет раздать допбаллы по 2 лр окончательно, т.к. мы ждали только вас).

**Comment by TonitaN** [comment]
Просьба изучить поведение программы на регулярке `(a|b)(a|b)` (которую должен был предъявить @geogreck !).

**Comment by Encapsulateed** [comment]
> Просьба изучить поведение программы на регулярке `(a|b)(a|b)` (которую должен был предъявить @geogreck !).
В код построения хэш карты для удаления одинаковых альтренатив были внесены соответствующие изменения. Ошибка была связана с тем, что я перестраивал мапу после каждого удаления одинаковой альтернативы. То есть в случае (a|b)(a|b) сначала удаляется альтернатива по а, затем по b, но поскольку аргумент альтернативы был всего один, такая нода считывалась невалидной, это и повлекло некорректный результат. 
Теперь поведение такое.
![graphviz (5)](https://github.com/Encapsulateed/tfl/assets/69109441/6d356ef5-f262-4305-893e-dc2be48baa5c)

**Comment by geogreck** [comment]
Процесс дебага будет долгим...

**Comment by TonitaN** [comment]
@geogreck , вы как тестировщик будете первым испытательным рубежом для новой версии. Если в тестах без решётки (для них можно использовать встроенных парсинг по регулярке) ваш фаззер покажет эквивалентность новых регулярок и старых, это знак, что пора отсылать правки мне на проверку. Но уж потратьте время, допишите несколько строчек и сделайте такую опцию тестирования.

**Comment by geogreck** [comment]
Хороший кейс для тестирования программы, спасибо, заиспользую, когда починю свою часть

**Comment by geogreck** [comment]
~~Если я правильно понял задумку, то вот~~
https://github.com/Encapsulateed/tfl/commit/c46ee82a180925c8e9fcbf84aaf72ea7f4fcedbc#diff-794fcfbc6f702c9e384dd6e2ab7a0f4de90ee5596baaea3560c0e2a2072fa28fR87-R90

Не, неправильно

Но с другой стороны теперь есть целых три вида тестирования:
1. Классический фазинг
2. Тест эквивалентности исходной регулярки и итоговой
3. Тест, что исходная регулярка и автомат распознают одно и то же

А лаба всё равно не работает...

**Comment by TonitaN** [comment]
@geogreck , надеюсь, вы не воспримете как игнор, если я не буду проверять ваш модуль прямо сейчас, а подожду, пока @Encapsulateed синхронизирует с ним свои правки. Ему очень полезно делать такие проверки, а то без внешнего цензора всё как-то не очень хорошо исправляется.

P.S. - Не хотите отревьюить фазз-модуль Ивана во второй ЛР? Это нетрудно сделать по мотивам ревью на вашего ученика.

**Comment by geogreck** [comment]
Ни о каком игноре не может быть и речи, я ведь сам честно пишу, что "Лаба не работает".

И, к сожалению, по причине того, что качество моего кода оставляет желать лучшего, не могу осмелиться проверить код Ивана, так как буду крайне некомпетентен.

**Comment by TonitaN** [comment]
Ну вы же делали ревью на Вячеслава, как раз на ту самую часть. Не настаиваю, но Ивану могла бы помочь ваша критика (между нами: баги одни и те же).

**Comment by geogreck** [comment]
Я уже хочу забыть эту лабу как страшный сон..

**Comment by TonitaN** [comment]
"Страшный сон" - это третья, а вторая - хорошая тренировка перед ней.

**Comment by Encapsulateed** [comment]
> Просьба изучить поведение программы на регулярке `(a|b)(a|b)` (которую должен был предъявить @geogreck !).

Приношу извинения за неверный ответ в предыдущий раз. Конечно же поведение на данном регулярном выражении должно быть следующим (и теперь оно такое): 
![graphviz](https://github.com/Encapsulateed/tfl/assets/69109441/01cb037c-cee8-4611-b0e5-09e2d251ac5f)

**Comment by Encapsulateed** [comment]
@geogreck официально заявляю, что я готов к тестированию!

**Comment by geogreck** [comment]
А поломку встроенной библиотеки регулярных выражений можно зачесть за допзадание? :)

Регулярка ^(a)(b)|c*((c)*)|a$ не распознает слово "a"...

Как допзадание прошу не засчитывать, потому что искать причину, почему так происходит, я не хочу

**Comment by TonitaN** [comment]
1. Когда пользуетесь стандартной библиотекой, нужно обрамлять регулярку с самой внешней альтернативой в скобки, потому что, например, `^a|b$` может успешно сопоставляться с `ab` (т.к. читается как `(^a)|(b$)`)/
2. А жаль, что не хотите, если поломка и вправду актуальна. Было бы 8 баллов - их тоже не надо? :)

P.S. - 8 баллов лишними не бывают, особенно вам.

**Comment by geogreck** [comment]
Спасибо, что в час ночи приходите на помощь. Скобки действительно помогли, но мне, думаю, даже 8 баллов не помогут

Дебаг продолжается...

**Comment by geogreck** [comment]
@Encapsulateed результаты тестирования неутешительны
1. (a|ac|((a)*)(a))*, Ваш автомат не распознает слово aaaaaaaaaaaaaaaaaaaaaaac
2. (b|(b|(a))(b)*)*(a)*, автомат не распознал слово ba

Конечно, такие ошибки случаются не на каждом первом регулярном выражении, поэтому можно считать это допустимой погрешностью плохой лабы, поэтому я продолжил тестирование дальше

Тестирование эквивалентности регулярных выражений
1. (a|((b(a))*)|(a)*)*|(c)*, не распознано aba
2. a(c*|cc*|((a)*))* не распознано aa
ошибки на каждом первом регулярном выражении

Фазинг страдает из-за тех же проблем, что и второй тест - очень плохо написанная конвертация автомата в регулярку

Работа продолжается...

**Comment by geogreck** [comment]
Вынужден сообщить, что предыдущий отчет об тестировании был сформирован не на самой последней версии кода Алексея. Приношу свои извинения.

Новая версия стала гораздо лучше, все баги из прошлого отчета на новой версии не воспроизводятся. В целом, часть Алексея стала работать лучше, но баги остаются
1. `(((a)*)a(b)*)ca` автомат ну очень странный
2. `(((b)*)bc*)*bс` аналогично
Учитвая схожесть регулярок, думаю баг в них один и тот же

Остальные тесты тоже как будто стали проходить чуточку лучше, но, к сожалению, всё ещё очень плохо. Всё-таки, преобразование в регулярное выражение написано просто отвратительно.

**Comment by TonitaN** [comment]
Если отвратительно (строятся экспоненциально большими и парсятся ну очень медленно), но эквивалентность семантик сохраняется, - это норма (т.е. на зачёт ок). Если бы было ещё и красиво и эффективно - получились бы 2 дополнительных балла, не так уж и много за страшный сон.

**Comment by geogreck** [comment]
Очень много тестов, где результаты расходятся (будь это проверка на эквивалентность или фаззинг). Так что до зачета ещё далеко.

**Comment by geogreck** [comment]
Конечно, я буду делать всё что есть в моих силах, чтобы наш поток получил свои доп баллы как можно скорее. Надеюсь, успею встать на семинар своей группы, на нем всё-таки как-то приятнее.

**Comment by geogreck** [comment]
Действительно, если мы оба будем на одном семинаре, может начаться война, в ходе которой я ещё и у доски оказаться могу..

**Comment by TonitaN** [comment]
Оффтоп: вот уж кому повезло с допзаданием, поскольку константа "любимый ЯП" у него была не установлена. Но баллы на допзадание задержу до простановки в ЭУ, пока наш герой не подтвердит, что язык и вправду "любимый" (т.е. что он действительно может написать на нём ЛР по ТФЯ).

**Comment by TonitaN** [comment]
Ну он же не один на второй ЛР. Вы и сами знаете, что без активной воли напарника сдать её проблематично (тем более, тестирующую часть).

P.S. - Уже похвалился допбаллами, подлец? =) Будет мне на экзамене рассказывать, как парсер "восстанавливался", чтобы каскад накопить. И нет, я не всех этим буду мучить - а только самых высокобалльников по допам.

**Comment by geogreck** [comment]
Ну теперь я точно доп задание делать не буду, зачем ещё эти доп вопросы на экзамене

**Comment by TonitaN** [comment]
Вам очень нравится, когда вас уговаривают сделать самому себе добро? Ок, мне не сложно, я ещё и лично завтра вам скажу. А доп вопросы в любом случае будут, если только не будет автомата (ну или нужно было идти на HoTT и ковыряться в зависимых типах, как верховный рефальщик потока, вот у него никаких доп вопросов уже не будет).

**Comment by geogreck** [comment]
Самое главное добро в моей жизни - 2 лаба, все ждут, когда они наконец получат свои доп баллы и поймут свои перспективы по данному курсу, поэтому все силы на нее

**Comment by TonitaN** [comment]
Хм, не задержать ли доп баллы по 3 ЛР, пока Старовойтов её не сдаст? Интересно, тоже сработает?

EDIT: Оффтоп уничтожен и прекращается, дабы не размножать компромат.

**Comment by geogreck** [comment]
Кажется, каждое мое сообщение делает меня ещё большим врагом народа.

**Comment by geogreck** [comment]
На 100-м, юбилейном комите, лаба кажется наконец-то достигла желаемого состояния - "Работает очень долго, иногда вовсе вылатает, но работает". Проверять это старшему преподователю я очень не рекомендую, информация скорее для @Encapsulateed (ну и возможно для кого-то, кто заходит сюда в надежде увидеть свои доп баллы).

**Comment by TonitaN** [comment]
Хорошо, мой младший коллега, подожду вашего пожелания передать ЛР на окончательную проверку.

**Comment by Encapsulateed** [comment]
Да действительно для приведённых ниже регулярных выражений строился некорректный автомат.
Что именно побудило меня упрощать поддеревья конкатенаций и шафлов, если их на любой глубине в их листовой вершине содержится ϵ или ∅ я не скажу.
Возможно теория формальных языков научит меня внимательности .....

P.S 
Досадная ошибка удалена.

> 1. `(((a)*)a(b)*)ca` автомат ну очень странный
> 2. `(((b)*)bc*)*bс` аналогично

**Comment by geogreck** [comment]
Считаю лабораторную работу достойной проверки и внимания старшего преподавателя. 
Из known-issue есть падение встроенной библиотеки регулярных выражений при слишком большой выходной регулярке, но, грубо говоря, когда этого не происходит, то лабораторная работа отрабатывает корректно.

**Comment by geogreck** [comment]
На самом деле, на примере этой работы можно изучать парадокс Тесея. Если все компоненты лабы были переписаны с нуля, но не все вместе за раз, это та же лаба или новая?

Хотя ладно, тестинговый модуль не менялся, так что это всё же настоящая лабораторная работа

**Comment by Encapsulateed** [comment]
Да и построение FSM осталось прежним..

**Comment by TonitaN** [comment]
Зачёт! Допбаллы за 2 ЛР ждём завтра!

**Comment by Encapsulateed** [comment]
Lets celebrate and ...

**Comment by geogreck** [comment]
Считаю это лучшим подарком на мой день рождения, хоть он и был в воскресенье

**Comment by TonitaN** [comment]
Из-за болезни чуть дольше выставлялись допбаллы, но всё-таки их все дождались...

**Comment by geogreck** [comment]
Спасибо, мы очень переживали за своих коллег!
